# Generated by Django 2.0.6 on 2018-11-25 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afterlecture', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=2000)),
                ('markup', models.CharField(choices=[('md', 'md'), ('html', 'html'), ('iframe', 'iframe'), ('img', 'img')], default='md', max_length=10)),
                ('citation', models.CharField(blank=True, default='', max_length=300)),
                ('citation_link', models.CharField(blank=True, default='', max_length=300)),
                ('related_content', models.ManyToManyField(blank=True, to='teach.Content')),
            ],
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=15)),
                ('additional_content', models.ManyToManyField(through='teach.AdditionalContent', to='teach.Content')),
                ('content_types_selected', models.ManyToManyField(blank=True, to='teach.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.CourseInstance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LectureStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.PositiveIntegerField()),
                ('multislide', models.BooleanField(default=False)),
                ('subordernum', models.PositiveIntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('layout', models.TextField(default="[{'t':'r','ch':[\n        {'t':'c','w':12,'ch':[\n                {'t':'n',\n                 'm':s[0]}\n                ]}\n            ]}\n        ]")),
                ('hastitle', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlideStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.PositiveIntegerField()),
                ('css_style', models.CharField(blank=True, default='', max_length=100)),
                ('animate', models.BooleanField(default=True)),
                ('print_title', models.BooleanField(default=False)),
                ('fragment_no', models.SmallIntegerField(default=0)),
                ('upto_level', models.SmallIntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Content')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Slide')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('restriction_kind', models.CharField(choices=[('none', 'none'), ('choice', 'choice'), ('number_of_choices', 'number_of_choices'), ('number', 'number')], default='none', max_length=25)),
                ('restriction_detail', models.TextField(blank=True, null=True)),
                ('eval_kind', models.CharField(choices=[('manual', 'manual'), ('accuracy', 'accuracy'), ('pct_off', 'pct_off')], default='manual', max_length=25)),
                ('eval_detail', models.TextField(blank=True, null=True)),
                ('eval_transform', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_human', models.BooleanField(default=False)),
                ('answertext', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('num_sample', models.PositiveIntegerField(default=0)),
                ('instant_answer', models.BooleanField(default=False)),
                ('tasks', models.ManyToManyField(blank=True, to='teach.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.BigIntegerField()),
                ('endtime', models.BigIntegerField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('tasklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.TaskList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.UserSubmission'),
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Task'),
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.ManyToManyField(through='teach.TaskAnswer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slide',
            name='contents',
            field=models.ManyToManyField(through='teach.SlideStructure', to='teach.Content'),
        ),
        migrations.AddField(
            model_name='lecturestructure',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Slide'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='slides',
            field=models.ManyToManyField(through='teach.LectureStructure', to='teach.Slide'),
        ),
        migrations.AddField(
            model_name='coursestructure',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Lecture'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='students',
            field=models.ManyToManyField(related_name='student', through='teach.CourseStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='lectures',
            field=models.ManyToManyField(through='teach.CourseStructure', to='teach.Lecture'),
        ),
        migrations.AddField(
            model_name='course',
            name='tasklists',
            field=models.ManyToManyField(blank=True, to='teach.TaskList'),
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teach.Topic'),
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teach.ContentType'),
        ),
        migrations.AddField(
            model_name='additionalcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Content'),
        ),
        migrations.AddField(
            model_name='additionalcontent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Course'),
        ),
    ]
