# Generated by Django 2.0.6 on 2018-08-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=2000)),
                ('markup', models.CharField(choices=[('md', 'md'), ('html', 'html')], default='md', max_length=4)),
                ('type', models.CharField(choices=[('def', 'Definition'), ('list', 'List'), ('task', 'Task'), ('ex', 'Example'), ('q', 'Question'), ('misc', 'Misc')], default='misc', max_length=4)),
                ('related_content', models.ManyToManyField(to='teach.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LectureStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.PositiveIntegerField()),
                ('multislide', models.BooleanField(default=False)),
                ('subordernum', models.PositiveIntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('layout', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SlideStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.PositiveIntegerField()),
                ('animate', models.BooleanField(default=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Content')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Slide')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='slide',
            name='contents',
            field=models.ManyToManyField(through='teach.SlideStructure', to='teach.Content'),
        ),
        migrations.AddField(
            model_name='lecturestructure',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Slide'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='slides',
            field=models.ManyToManyField(through='teach.LectureStructure', to='teach.Slide'),
        ),
        migrations.AddField(
            model_name='coursestructure',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Lecture'),
        ),
        migrations.AddField(
            model_name='course',
            name='slides',
            field=models.ManyToManyField(through='teach.CourseStructure', to='teach.Lecture'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Topic'),
        ),
    ]
