# Generated by Django 2.0.6 on 2018-11-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='imagelink',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
