# Generated by Django 2.2.6 on 2019-10-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0002_remove_course_additional_lecture_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='format',
            field=models.CharField(choices=[('md', 'md'), ('html', 'html'), ('python', 'python')], default='md', max_length=10),
        ),
    ]
