# Generated by Django 2.0.6 on 2018-12-11 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teach', '0002_task_imagelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstance',
            name='teachers',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='admins',
            field=models.ManyToManyField(related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
