# Generated by Django 2.1.5 on 2019-01-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0003_auto_20181211_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswer',
            name='needs_human',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='submitted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
